import { DatabaseIntrospectionResult, TableColumn, TableSchema } from '@/types/supabase';

// Map SQL types to Drizzle column helpers
function mapToDrizzleType(col: TableColumn): string {
  const t = col.type.toLowerCase();
  const name = col.name;

  if (col.isPrimary && (t === 'serial' || (t.includes('int') && col.defaultValue?.includes('nextval')))) {
    return `serial('${name}').primaryKey()`;
  }
  if (t === 'uuid') {
    let s = `uuid('${name}')`;
    if (col.defaultValue?.includes('gen_random_uuid') || col.defaultValue?.includes('uuid_generate')) {
      s += `.defaultRandom()`;
    }
    if (col.isPrimary) s += `.primaryKey()`;
    if (!col.isNullable && !col.isPrimary) s += `.notNull()`;
    return s;
  }
  if (t === 'text' || t.startsWith('varchar') || t === 'char') {
    let s = `text('${name}')`;
    if (col.defaultValue) s += `.default(${col.defaultValue.replace(/::text$/, '')})`;
    if (col.isPrimary) s += `.primaryKey()`;
    if (!col.isNullable && !col.isPrimary) s += `.notNull()`;
    return s;
  }
  if (t === 'boolean' || t === 'bool') {
    let s = `boolean('${name}')`;
    if (col.defaultValue) s += `.default(${col.defaultValue})`;
    if (!col.isNullable) s += `.notNull()`;
    return s;
  }
  if (t === 'integer' || t === 'int' || t === 'int4') {
    let s = `integer('${name}')`;
    if (col.defaultValue && !col.defaultValue.includes('nextval')) s += `.default(${col.defaultValue})`;
    if (col.isPrimary) s += `.primaryKey()`;
    if (!col.isNullable && !col.isPrimary) s += `.notNull()`;
    return s;
  }
  if (t === 'bigint' || t === 'int8') {
    let s = `bigint('${name}', { mode: 'number' })`;
    if (col.isPrimary) s += `.primaryKey()`;
    if (!col.isNullable && !col.isPrimary) s += `.notNull()`;
    return s;
  }
  if (t === 'jsonb' || t === 'json') {
    let s = `jsonb('${name}')`;
    if (col.defaultValue) s += `.$defaultFn(() => ({}))`;
    if (!col.isNullable) s += `.notNull()`;
    return s;
  }
  if (t === 'timestamptz' || t === 'timestamp with time zone') {
    let s = `timestamp('${name}', { withTimezone: true, mode: 'string' })`;
    if (col.defaultValue?.includes('now')) s += `.defaultNow()`;
    if (!col.isNullable) s += `.notNull()`;
    return s;
  }
  if (t === 'timestamp' || t === 'timestamp without time zone') {
    let s = `timestamp('${name}', { mode: 'string' })`;
    if (col.defaultValue?.includes('now')) s += `.defaultNow()`;
    if (!col.isNullable) s += `.notNull()`;
    return s;
  }
  if (t.includes('vector')) {
    return `customVector('${name}').notNull()`;
  }
  // Fallback to text
  let s = `text('${name}')`;
  if (!col.isNullable && !col.isPrimary) s += `.notNull()`;
  return s;
}

export function generateDrizzleSchema(result: DatabaseIntrospectionResult): string {
  const hasVector = result.tables.some(t => t.columns.some(c => c.type.includes('vector')));
  const imports = new Set<string>(['pgTable', 'text', 'integer', 'boolean', 'timestamp', 'uuid']);

  result.tables.forEach(t => {
    t.columns.forEach(c => {
      const type = c.type.toLowerCase();
      if (type.includes('serial')) imports.add('serial');
      if (type.includes('bigint') || type.includes('int8')) imports.add('bigint');
      if (type.includes('json')) imports.add('jsonb');
    });
  });

  let out = `/**
 * Drizzle ORM Schema
 * Auto-generated by SupaSync for Supabase project: ${result.projectInfo.name || result.projectInfo.url}
 * Generated at: ${new Date().toISOString()}
 */

import { ${Array.from(imports).join(', ')}, customType } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';\n\n`;

  if (hasVector) {
    out += `// Support pour l'extension pgvector
const customVector = customType<{ data: number[]; driverData: string }>({
  dataType() {
    return 'vector(1536)';
  },
  toDriver(val: number[]) {
    return JSON.stringify(val);
  },
  fromDriver(val: string) {
    return JSON.parse(val);
  },
});\n\n`;
  }

  // Tables definition
  result.tables.forEach(table => {
    out += `// Table: ${table.name}${table.description ? ' - ' + table.description : ''}\n`;
    out += `export const ${table.name} = pgTable('${table.name}', {\n`;
    table.columns.forEach(col => {
      let line = `  ${col.name}: ${mapToDrizzleType(col)}`;
      if (col.foreignKey) {
        line += `.references(() => ${col.foreignKey.targetTable}.${col.foreignKey.targetColumn}`;
        if (col.foreignKey.onDelete) {
          line += `, { onDelete: '${col.foreignKey.onDelete.toLowerCase()}' }`;
        }
        line += `)`;
      }
      line += `,`;
      out += `${line}\n`;
    });
    out += `});\n\n`;
  });

  // Relations definition
  result.tables.forEach(table => {
    const outboundRels = result.relationships.filter(r => r.sourceTable === table.name);
    const inboundRels = result.relationships.filter(r => r.targetTable === table.name);

    if (outboundRels.length > 0 || inboundRels.length > 0) {
      out += `export const ${table.name}Relations = relations(${table.name}, ({ one, many }) => ({\n`;
      outboundRels.forEach(r => {
        out += `  ${r.targetTable}: one(${r.targetTable}, {\n`;
        out += `    fields: [${table.name}.${r.sourceColumn}],\n`;
        out += `    references: [${r.targetTable}.${r.targetColumn}],\n`;
        out += `  }),\n`;
      });
      inboundRels.forEach(r => {
        out += `  ${r.sourceTable}: many(${r.sourceTable}),\n`;
      });
      out += `}));\n\n`;
    }
  });

  return out;
}

// Map SQL types to Prisma scalar types
function mapToPrismaType(col: TableColumn): string {
  const t = col.type.toLowerCase();
  let base = 'String';
  if (t === 'uuid') base = 'String';
  else if (t === 'text' || t.startsWith('varchar') || t === 'char') base = 'String';
  else if (t === 'boolean' || t === 'bool') base = 'Boolean';
  else if (t === 'integer' || t === 'int' || t === 'int4' || t === 'serial') base = 'Int';
  else if (t === 'bigint' || t === 'int8') base = 'BigInt';
  else if (t === 'float' || t === 'float8' || t === 'numeric' || t === 'double precision') base = 'Float';
  else if (t.includes('json')) base = 'Json';
  else if (t.includes('timestamp') || t.includes('date')) base = 'DateTime';
  else if (t.includes('vector')) base = 'Unsupported("vector(1536)")';

  return col.isNullable && !col.isPrimary ? `${base}?` : base;
}

export function generatePrismaSchema(result: DatabaseIntrospectionResult): string {
  let out = `// Prisma Schema for Supabase
// Auto-generated by SupaSync
// Database: ${result.projectInfo.name || 'Supabase PostgreSQL'}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

generator client {
  provider = "prisma-client-js"
}\n\n`;

  result.tables.forEach(table => {
    out += `model ${capitalize(table.name)} {\n`;
    table.columns.forEach(col => {
      let line = `  ${col.name.padEnd(20)} ${mapToPrismaType(col).padEnd(14)}`;
      if (col.isPrimary) {
        line += ' @id';
        if (col.type === 'uuid' || col.defaultValue?.includes('random') || col.defaultValue?.includes('uuid')) {
          line += ' @default(uuid())';
        } else if (col.type.includes('serial') || col.defaultValue?.includes('nextval')) {
          line += ' @default(autoincrement())';
        }
      } else if (col.defaultValue?.includes('now()')) {
        line += ' @default(now())';
      } else if (col.defaultValue && !col.defaultValue.includes('nextval')) {
        line += ` @default(${col.defaultValue.replace(/::[a-z0-9_]+$/i, '')})`;
      }

      out += `${line}\n`;
    });

    // Relations in model
    const outbound = result.relationships.filter(r => r.sourceTable === table.name);
    outbound.forEach(r => {
      out += `  ${r.targetTable.padEnd(20)} ${capitalize(r.targetTable).padEnd(14)} @relation(fields: [${r.sourceColumn}], references: [${r.targetColumn}])\n`;
    });

    const inbound = result.relationships.filter(r => r.targetTable === table.name);
    inbound.forEach(r => {
      out += `  ${(r.sourceTable + 'List').padEnd(20)} ${capitalize(r.sourceTable)}[]\n`;
    });

    out += `\n  @@map("${table.name}")\n`;
    out += `}\n\n`;
  });

  return out;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

export function generateTypeScriptTypes(result: DatabaseIntrospectionResult): string {
  let out = `/**
 * TypeScript Supabase Database Types
 * Generated by SupaSync
 * Compatible with @supabase/supabase-js createClient<Database>()
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {\n`;

  result.tables.forEach(table => {
    out += `      ${table.name}: {\n`;
    out += `        Row: {\n`;
    table.columns.forEach(col => {
      out += `          ${col.name}: ${mapToTSType(col, false)};\n`;
    });
    out += `        };\n`;

    out += `        Insert: {\n`;
    table.columns.forEach(col => {
      const opt = col.isNullable || col.defaultValue !== undefined || col.isPrimary ? '?' : '';
      out += `          ${col.name}${opt}: ${mapToTSType(col, true)};\n`;
    });
    out += `        };\n`;

    out += `        Update: {\n`;
    table.columns.forEach(col => {
      out += `          ${col.name}?: ${mapToTSType(col, true)};\n`;
    });
    out += `        };\n`;

    // Foreign key relationships
    const rels = result.relationships.filter(r => r.sourceTable === table.name);
    out += `        Relationships: [\n`;
    rels.forEach(r => {
      out += `          {\n`;
      out += `            foreignKeyName: "fk_${table.name}_${r.sourceColumn}";\n`;
      out += `            columns: ["${r.sourceColumn}"];\n`;
      out += `            referencedRelation: "${r.targetTable}";\n`;
      out += `            referencedColumns: ["${r.targetColumn}"];\n`;
      out += `          },\n`;
    });
    out += `        ];\n`;
    out += `      };\n`;
  });

  out += `    };\n`;
  out += `    Views: {\n`;
  result.views.forEach(v => {
    out += `      ${v.name}: {\n        Row: {\n`;
    v.columns.forEach(col => {
      out += `          ${col.name}: ${mapToTSType(col, false)};\n`;
    });
    out += `        };\n      };\n`;
  });
  out += `    };\n`;
  out += `    Functions: Record<string, never>;\n`;
  out += `  };\n`;
  out += `}\n`;

  return out;
}

function mapToTSType(col: TableColumn, forInsert: boolean): string {
  const t = col.type.toLowerCase();
  let base = 'string';
  if (t === 'uuid' || t === 'text' || t.startsWith('varchar') || t === 'char') base = 'string';
  else if (t === 'boolean' || t === 'bool') base = 'boolean';
  else if (t.includes('int') || t === 'serial' || t === 'float' || t === 'numeric') base = 'number';
  else if (t.includes('json')) base = 'Json';
  else if (t.includes('vector')) base = 'number[]';
  else if (t.includes('date') || t.includes('time')) base = 'string';

  if (!forInsert && col.isNullable) {
    return `${base} | null`;
  }
  return base;
}

export function generateSqlDDL(result: DatabaseIntrospectionResult): string {
  let out = `-- ========================================================
-- SupaSync - Script de Définition & Configuration de Base
-- Projet: ${result.projectInfo.name || result.projectInfo.url}
-- Date: ${new Date().toISOString()}
-- ========================================================

-- Extensions PostgreSQL recommandées
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
`;

  if (result.tables.some(t => t.columns.some(c => c.type.includes('vector')))) {
    out += `CREATE EXTENSION IF NOT EXISTS "vector";\n`;
  }

  out += `\n`;

  // Create tables
  result.tables.forEach(table => {
    out += `-- --------------------------------------------------------\n`;
    out += `-- Table: ${table.name}\n`;
    out += `-- --------------------------------------------------------\n`;
    out += `CREATE TABLE IF NOT EXISTS public.${table.name} (\n`;

    const colsSql = table.columns.map(col => {
      let s = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.isPrimary) s += ` PRIMARY KEY`;
      if (!col.isNullable && !col.isPrimary) s += ` NOT NULL`;
      if (col.defaultValue) s += ` DEFAULT ${col.defaultValue}`;
      return s;
    });

    out += colsSql.join(',\n');
    out += `\n);\n\n`;

    // Foreign keys
    table.columns
      .filter(c => c.foreignKey)
      .forEach(c => {
        const fk = c.foreignKey!;
        out += `ALTER TABLE public.${table.name} \n`;
        out += `  DROP CONSTRAINT IF EXISTS fk_${table.name}_${c.name},\n`;
        out += `  ADD CONSTRAINT fk_${table.name}_${c.name} \n`;
        out += `  FOREIGN KEY (${c.name}) REFERENCES public.${fk.targetTable}(${fk.targetColumn})`;
        if (fk.onDelete) out += ` ON DELETE ${fk.onDelete}`;
        out += `;\n\n`;
      });

    // RLS Activation
    out += `-- Activation de Row Level Security (RLS)\n`;
    out += `ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;\n\n`;

    // Policies
    if (table.policies && table.policies.length > 0) {
      table.policies.forEach(p => {
        out += `CREATE POLICY "${p.name}" ON public.${table.name}\n`;
        out += `  FOR ${p.command} TO ${p.roles.join(', ')}\n`;
        if (p.definition) out += `  USING (${p.definition})\n`;
        if (p.check) out += `  WITH CHECK (${p.check})\n`;
        out += `;\n\n`;
      });
    } else {
      // Default safe policy template
      out += `-- Stratégie de sécurité par défaut pour ${table.name}\n`;
      out += `CREATE POLICY "Authenticated users can select ${table.name}" \n`;
      out += `  ON public.${table.name} FOR SELECT TO authenticated USING (true);\n\n`;
    }
  });

  // Recommended indexes
  out += `-- ========================================================\n`;
  out += `-- Index de Performance pour Clés Étrangères\n`;
  out += `-- ========================================================\n`;
  result.relationships.forEach(rel => {
    out += `CREATE INDEX IF NOT EXISTS idx_${rel.sourceTable}_${rel.sourceColumn} \n`;
    out += `  ON public.${rel.sourceTable}(${rel.sourceColumn});\n\n`;
  });

  return out;
}

export function generateSqlRLSHardening(result: DatabaseIntrospectionResult): string {
  let out = `-- ========================================================\n`;
  out += `-- Audit & Durcissement Sécurité RLS pour Supabase\n`;
  out += `-- Généré automatiquement par SupaSync\n`;
  out += `-- Score de sécurité actuel: ${result.securityAudit.score}/100\n`;
  out += `-- ========================================================\n\n`;

  result.tables.forEach(table => {
    out += `-- 1. Forcer RLS sur ${table.name}\n`;
    out += `ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;\n`;

    const hasUserId = table.columns.some(c => c.name === 'user_id' || c.name === 'author_id');
    const isPublicLookup = ['categories', 'products', 'articles', 'plans'].includes(table.name);

    if (hasUserId) {
      const userCol = table.columns.find(c => c.name === 'user_id' || c.name === 'author_id')!.name;
      out += `CREATE POLICY "Users can only read own rows on ${table.name}"\n`;
      out += `  ON public.${table.name} FOR SELECT TO authenticated\n`;
      out += `  USING (auth.uid() = ${userCol});\n\n`;

      out += `CREATE POLICY "Users can insert own rows on ${table.name}"\n`;
      out += `  ON public.${table.name} FOR INSERT TO authenticated\n`;
      out += `  WITH CHECK (auth.uid() = ${userCol});\n\n`;

      out += `CREATE POLICY "Users can update own rows on ${table.name}"\n`;
      out += `  ON public.${table.name} FOR UPDATE TO authenticated\n`;
      out += `  USING (auth.uid() = ${userCol});\n\n`;
    } else if (isPublicLookup) {
      out += `CREATE POLICY "Public read for ${table.name}"\n`;
      out += `  ON public.${table.name} FOR SELECT TO anon, authenticated\n`;
      out += `  USING (true);\n\n`;
    } else {
      out += `CREATE POLICY "Authenticated users can read ${table.name}"\n`;
      out += `  ON public.${table.name} FOR SELECT TO authenticated\n`;
      out += `  USING (true);\n\n`;
    }
  });

  return out;
}

export function generateSeedScript(result: DatabaseIntrospectionResult, format: 'sql' | 'typescript'): string {
  if (format === 'sql') {
    let out = `-- Supabase Mock Seed Data\n-- Generated by SupaSync\n\n`;
    result.tables.forEach(table => {
      if (table.sampleRows && table.sampleRows.length > 0) {
        out += `-- Insert mock records into ${table.name}\n`;
        table.sampleRows.forEach(row => {
          const keys = Object.keys(row);
          const vals = keys.map(k => {
            const v = row[k];
            if (v === null) return 'NULL';
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (typeof v === 'number') return v;
            return `'${String(v).replace(/'/g, "''")}'`;
          });
          out += `INSERT INTO public.${table.name} (${keys.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT DO NOTHING;\n`;
        });
        out += `\n`;
      }
    });
    return out;
  }

  // TypeScript Seed script
  let out = `import { createClient } from '@supabase/supabase-js';
import type { Database } from './types/database.types';

const supabase = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY! // Bypass RLS for seeding
);

export async function seedDatabase() {
  console.log('🌱 Seeding database...');\n`;

  result.tables.forEach(table => {
    if (table.sampleRows && table.sampleRows.length > 0) {
      out += `  // Seed ${table.name}\n`;
      out += `  await supabase.from('${table.name}').upsert(${JSON.stringify(table.sampleRows, null, 2)});\n\n`;
    }
  });

  out += `  console.log('✅ Database seeded successfully!');
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  seedDatabase().catch(console.error);
}\n`;

  return out;
}

export function generateEnvFile(result: DatabaseIntrospectionResult): string {
  const url = result.projectInfo.url || 'https://xyzcompany.supabase.co';
  const ref = result.projectInfo.ref || 'xyzcompany';

  return `# Supabase Configuration Environment Variables
# Auto-generated by SupaSync

# Public client credentials (safe in browser)
NEXT_PUBLIC_SUPABASE_URL="${url}"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
VITE_SUPABASE_URL="${url}"
VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

# Secret Service Role Key (NEVER expose to client browser)
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

# Direct PostgreSQL Connection Strings (Prisma, Drizzle, psql)
# Transaction pooler (port 6543)
DATABASE_URL="postgresql://postgres.${ref}:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Session pooler / direct migrations (port 5432)
DIRECT_URL="postgresql://postgres.${ref}:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"
`;
}

export function generateClientSetup(result: DatabaseIntrospectionResult, target: 'react' | 'nextjs' | 'node' | 'python' | 'flutter'): string {
  if (target === 'react') {
    return `// src/lib/supabaseClient.ts
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/database.types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '${result.projectInfo.url}';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'YOUR_ANON_KEY';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Example usage:
// const { data, error } = await supabase.from('${result.tables[0]?.name || 'users'}').select('*');
`;
  }

  if (target === 'nextjs') {
    return `// utils/supabase/client.ts (Next.js Client Components)
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from '@/types/database.types';

export function createClient() {
  return createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

// utils/supabase/server.ts (Next.js Server Components & Server Actions)
import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';
import type { Database } from '@/types/database.types';

export function createServerSupabaseClient() {
  const cookieStore = cookies();
  return createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch {}
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options });
          } catch {}
        },
      },
    }
  );
}
`;
  }

  if (target === 'node') {
    return `// server/db/supabaseAdmin.ts (Node.js / Express Backend)
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/database.types';

export const supabaseAdmin = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!, // Admin privilege
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  }
);
`;
  }

  if (target === 'python') {
    return `# supabase_client.py
import os
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL", "${result.projectInfo.url}")
key: str = os.environ.get("SUPABASE_KEY", "YOUR_KEY")
supabase: Client = create_client(url, key)

# Query example
response = supabase.table("${result.tables[0]?.name || 'users'}").select("*").execute()
print(response.data)
`;
  }

  // Flutter
  return `// supabase_client.dart
import 'package:supabase_flutter/supabase_flutter.dart';

Future<void> initSupabase() async {
  await Supabase.initialize(
    url: '${result.projectInfo.url}',
    anonKey: 'YOUR_ANON_KEY',
  );
}

final supabase = Supabase.instance.client;
`;
}
