import { DatabaseIntrospectionResult, TableColumn, TableSchema, Relationship } from '@/types/supabase';

export interface LovableProjectTemplate {
  id: string;
  name: string;
  description: string;
  lovableUrl: string;
  data: DatabaseIntrospectionResult;
}

/**
 * Generate Lovable's standard client integration file: src/integrations/supabase/client.ts
 */
export function generateLovableClient(result: DatabaseIntrospectionResult): string {
  const url = result.projectInfo.url || 'https://xyzcompany.supabase.co';

  return `// src/integrations/supabase/client.ts
// This file is automatically generated by SupaSync for your Lovable.dev project
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "${url}";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...";

// Import the supabase client like this in your Lovable components:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
`;
}

/**
 * Generate Lovable's exact TypeScript database schema definition: src/integrations/supabase/types.ts
 */
export function generateLovableTypes(result: DatabaseIntrospectionResult): string {
  let out = `// src/integrations/supabase/types.ts
// Lovable-compatible TypeScript Database Types
// Auto-generated by SupaSync from your live Supabase project

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {\n`;

  result.tables.forEach((table) => {
    out += `      ${table.name}: {\n`;
    out += `        Row: {\n`;
    table.columns.forEach((col) => {
      out += `          ${col.name}: ${mapSqlToTs(col.type, col.isNullable)};\n`;
    });
    out += `        };\n`;

    out += `        Insert: {\n`;
    table.columns.forEach((col) => {
      const isOptional = col.isNullable || col.defaultValue !== undefined || col.isPrimary;
      out += `          ${col.name}${isOptional ? '?' : ''}: ${mapSqlToTs(col.type, false)};\n`;
    });
    out += `        };\n`;

    out += `        Update: {\n`;
    table.columns.forEach((col) => {
      out += `          ${col.name}?: ${mapSqlToTs(col.type, false)};\n`;
    });
    out += `        };\n`;

    // Foreign key relationships
    const rels = result.relationships.filter((r) => r.sourceTable === table.name);
    out += `        Relationships: [\n`;
    rels.forEach((r) => {
      out += `          {\n`;
      out += `            foreignKeyName: "fk_${table.name}_${r.sourceColumn}";\n`;
      out += `            columns: ["${r.sourceColumn}"];\n`;
      out += `            isOneToOne: ${r.type === '1:1' ? 'true' : 'false'};\n`;
      out += `            referencedRelation: "${r.targetTable}";\n`;
      out += `            referencedColumns: ["${r.targetColumn}"];\n`;
      out += `          },\n`;
    });
    out += `        ];\n`;
    out += `      };\n`;
  });

  out += `    };\n`;
  out += `    Views: {\n`;
  result.views.forEach((v) => {
    out += `      ${v.name}: {\n        Row: {\n`;
    v.columns.forEach((col) => {
      out += `          ${col.name}: ${mapSqlToTs(col.type, col.isNullable)};\n`;
    });
    out += `        };\n      };\n`;
  });
  out += `    };\n`;
  out += `    Functions: Record<string, never>;\n`;
  out += `    Enums: Record<string, never>;\n`;
  out += `    CompositeTypes: Record<string, never>;\n`;
  out += `  };\n`;
  out += `};\n`;

  return out;
}

function mapSqlToTs(type: string, isNullable: boolean): string {
  const t = type.toLowerCase();
  let base = 'string';
  if (t === 'uuid' || t === 'text' || t.startsWith('varchar') || t === 'char') base = 'string';
  else if (t === 'boolean' || t === 'bool') base = 'boolean';
  else if (t.includes('int') || t === 'serial' || t === 'float' || t === 'numeric') base = 'number';
  else if (t.includes('json')) base = 'Json';
  else if (t.includes('vector')) base = 'number[]';
  else if (t.includes('date') || t.includes('time')) base = 'string';

  return isNullable ? `${base} | null` : base;
}

/**
 * Generate full Lovable Data Transfer SQL Dump (Schema + Sample Records + RLS)
 */
export function generateLovableDataTransferSql(result: DatabaseIntrospectionResult): string {
  let sql = `-- ========================================================\n`;
  sql += `-- SCRIPT DE TRANSFERT SUPABASE <-> LOVABLE\n`;
  sql += `-- Projet: ${result.projectInfo.name || result.projectInfo.url}\n`;
  sql += `-- Généré le: ${new Date().toISOString()}\n`;
  sql += `-- Ce script crée la structure et injecte les données dans Supabase\n`;
  sql += `-- pour que votre application Lovable fonctionne immédiatement.\n`;
  sql += `-- ========================================================\n\n`;

  sql += `-- 1. Extensions indispensables\n`;
  sql += `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`;
  sql += `CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n\n`;

  // Create tables
  result.tables.forEach((table) => {
    sql += `-- Table ${table.name}\n`;
    sql += `CREATE TABLE IF NOT EXISTS public.${table.name} (\n`;
    const colDefs = table.columns.map((col) => {
      let d = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.isPrimary) d += ` PRIMARY KEY`;
      if (!col.isNullable && !col.isPrimary) d += ` NOT NULL`;
      if (col.defaultValue) d += ` DEFAULT ${col.defaultValue}`;
      return d;
    });
    sql += colDefs.join(',\n');
    sql += `\n);\n\n`;

    // Enable RLS
    sql += `ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;\n\n`;

    // RLS Policy for Lovable
    sql += `-- Politiques RLS pour Lovable\n`;
    const hasUserId = table.columns.some((c) => c.name === 'user_id');
    if (hasUserId) {
      sql += `DROP POLICY IF EXISTS "${table.name}_user_policy" ON public.${table.name};\n`;
      sql += `CREATE POLICY "${table.name}_user_policy" ON public.${table.name}\n`;
      sql += `  FOR ALL TO authenticated\n`;
      sql += `  USING (auth.uid() = user_id)\n`;
      sql += `  WITH CHECK (auth.uid() = user_id);\n\n`;

      sql += `DROP POLICY IF EXISTS "${table.name}_public_read" ON public.${table.name};\n`;
      sql += `CREATE POLICY "${table.name}_public_read" ON public.${table.name}\n`;
      sql += `  FOR SELECT TO anon, authenticated\n`;
      sql += `  USING (true);\n\n`;
    } else {
      sql += `DROP POLICY IF EXISTS "${table.name}_access" ON public.${table.name};\n`;
      sql += `CREATE POLICY "${table.name}_access" ON public.${table.name}\n`;
      sql += `  FOR ALL TO anon, authenticated\n`;
      sql += `  USING (true)\n`;
      sql += `  WITH CHECK (true);\n\n`;
    }
  });

  // Inject sample data rows
  sql += `-- ========================================================\n`;
  sql += `-- 2. DONNÉES DE TRANSFERT (DATA SEEDING POUR LOVABLE)\n`;
  sql += `-- ========================================================\n\n`;

  result.tables.forEach((table) => {
    if (table.sampleRows && table.sampleRows.length > 0) {
      sql += `-- Données transférées pour "${table.name}" (${table.sampleRows.length} lignes)\n`;
      table.sampleRows.forEach((row) => {
        const keys = Object.keys(row);
        const values = keys.map((k) => {
          const v = row[k];
          if (v === null || v === undefined) return 'NULL';
          if (typeof v === 'boolean') return v ? 'true' : 'false';
          if (typeof v === 'number') return v;
          if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
          return `'${String(v).replace(/'/g, "''")}'`;
        });
        sql += `INSERT INTO public.${table.name} (${keys.join(', ')}) VALUES (${values.join(', ')}) ON CONFLICT DO NOTHING;\n`;
      });
      sql += `\n`;
    }
  });

  return sql;
}

/**
 * Parse Lovable types.ts code to extract table schema and relationships
 */
export function parseLovableTypesCode(typesContent: string): DatabaseIntrospectionResult {
  const tables: TableSchema[] = [];
  const relationships: Relationship[] = [];

  // Match Tables block: Tables: { ... }
  const tablesBlockMatch = typesContent.match(/Tables:\s*\{([\s\S]*?)\n\s*\}\s*;\s*\n\s*Views:/);
  const tablesContent = tablesBlockMatch ? tablesBlockMatch[1] : typesContent;

  // Split by table definitions: tableName: { Row: { ... }, Insert: { ... } }
  const tableRegex = /([a-zA-Z0-9_]+):\s*\{\s*Row:\s*\{([\s\S]*?)\}\s*;/g;
  let match: RegExpExecArray | null;

  while ((match = tableRegex.exec(tablesContent)) !== null) {
    const tableName = match[1];
    const rowContent = match[2];

    const columns: TableColumn[] = [];
    const colRegex = /([a-zA-Z0-9_]+)(\?)?:\s*([a-zA-Z0-9_\[\]\| ]+);/g;
    let colMatch: RegExpExecArray | null;

    while ((colMatch = colRegex.exec(rowContent)) !== null) {
      const colName = colMatch[1];
      const rawType = colMatch[3].trim();
      const isNullable = rawType.includes('null') || !!colMatch[2];
      const isPrimary = colName === 'id' || colName === `${tableName}_id`;

      // Map TypeScript type back to Postgres
      let pgType = 'text';
      if (rawType.includes('number')) pgType = 'integer';
      else if (rawType.includes('boolean')) pgType = 'boolean';
      else if (colName.includes('_at') || colName.includes('date')) pgType = 'timestamptz';
      else if (colName === 'id' && !rawType.includes('number')) pgType = 'uuid';
      else if (rawType.includes('Json') || rawType.includes('Record')) pgType = 'jsonb';

      let foreignKey: TableColumn['foreignKey'] | undefined;
      if (colName.endsWith('_id') && colName !== 'id') {
        const targetTable = colName.replace(/_id$/, '') + 's';
        foreignKey = { targetTable, targetColumn: 'id' };
        relationships.push({
          id: `rel_${tableName}_${colName}`,
          sourceTable: tableName,
          sourceColumn: colName,
          targetTable,
          targetColumn: 'id',
          type: 'N:1',
        });
      }

      columns.push({
        name: colName,
        type: pgType,
        isPrimary,
        isNullable,
        defaultValue: isPrimary && pgType === 'uuid' ? 'gen_random_uuid()' : undefined,
        foreignKey,
      });
    }

    tables.push({
      name: tableName,
      schema: 'public',
      columns,
      primaryKeys: ['id'],
      rlsEnabled: true,
      rowCount: 3,
      sampleRows: [
        { id: 'lovable-mock-1', created_at: new Date().toISOString() },
      ],
    });
  }

  return {
    projectInfo: {
      url: 'https://lovable-imported.supabase.co',
      ref: 'lovable-imported',
      name: 'Projet Importé de Lovable.dev',
      region: 'eu-central-1',
      latencyMs: 35,
      checkedAt: new Date().toISOString(),
      connectedVia: 'url_key',
    },
    tables,
    views: [],
    relationships,
    storageBuckets: [
      { id: 'lovable-assets', name: 'lovable-assets', public: true },
    ],
    securityAudit: {
      score: 95,
      rlsDisabledCount: 0,
      missingIndexesCount: 0,
      totalTables: tables.length,
      issues: [],
    },
  };
}

/**
 * Pre-configured Lovable App Templates
 */
export const LOVABLE_PRESETS: LovableProjectTemplate[] = [
  {
    id: 'lovable-crm-saas',
    name: 'Lovable CRM & Leads Management',
    description: 'Application Lovable de gestion de pipeline commercial, contacts clients, opportunités et activités.',
    lovableUrl: 'https://lovable.dev/projects/crm-leads-pipeline',
    data: {
      projectInfo: {
        url: 'https://crm-lovable.supabase.co',
        ref: 'crm-lovable-01',
        name: 'Lovable CRM Database',
        region: 'eu-west-1',
        latencyMs: 38,
        checkedAt: new Date().toISOString(),
        connectedVia: 'demo_preset',
      },
      tables: [
        {
          name: 'leads',
          schema: 'public',
          description: 'Prospects et contacts qualifiés',
          primaryKeys: ['id'],
          rlsEnabled: true,
          rowCount: 45,
          columns: [
            { name: 'id', type: 'uuid', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { name: 'user_id', type: 'uuid', isPrimary: false, isNullable: false },
            { name: 'company_name', type: 'text', isPrimary: false, isNullable: false },
            { name: 'contact_name', type: 'text', isPrimary: false, isNullable: false },
            { name: 'email', type: 'text', isPrimary: false, isNullable: false },
            { name: 'status', type: 'text', isPrimary: false, isNullable: false, defaultValue: "'new'" },
            { name: 'deal_value', type: 'integer', isPrimary: false, isNullable: false, defaultValue: '5000' },
            { name: 'created_at', type: 'timestamptz', isPrimary: false, isNullable: false, defaultValue: 'now()' },
          ],
          sampleRows: [
            { id: 'lead-1', user_id: 'usr-lov-1', company_name: 'TechCorp SAS', contact_name: 'Julie Robert', email: 'j.robert@techcorp.fr', status: 'qualified', deal_value: 12500, created_at: '2026-03-01T09:00:00Z' },
            { id: 'lead-2', user_id: 'usr-lov-1', company_name: 'InovApp', contact_name: 'David Blanc', email: 'david@inovapp.io', status: 'proposal_sent', deal_value: 8000, created_at: '2026-03-02T11:30:00Z' },
            { id: 'lead-3', user_id: 'usr-lov-2', company_name: 'SolarGreen', contact_name: 'Sophie Moreau', email: 'smoreau@solargreen.com', status: 'won', deal_value: 24000, created_at: '2026-03-03T15:00:00Z' },
          ],
        },
        {
          name: 'deals',
          schema: 'public',
          description: 'Opportunités du pipeline de vente',
          primaryKeys: ['id'],
          rlsEnabled: true,
          rowCount: 18,
          columns: [
            { name: 'id', type: 'uuid', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { name: 'lead_id', type: 'uuid', isPrimary: false, isNullable: false, foreignKey: { targetTable: 'leads', targetColumn: 'id', onDelete: 'CASCADE' } },
            { name: 'stage', type: 'text', isPrimary: false, isNullable: false, defaultValue: "'negotiation'" },
            { name: 'probability', type: 'integer', isPrimary: false, isNullable: false, defaultValue: '60' },
            { name: 'expected_close', type: 'timestamptz', isPrimary: false, isNullable: true },
            { name: 'created_at', type: 'timestamptz', isPrimary: false, isNullable: false, defaultValue: 'now()' },
          ],
          sampleRows: [
            { id: 'deal-101', lead_id: 'lead-1', stage: 'negotiation', probability: 75, created_at: '2026-03-02T10:00:00Z' },
            { id: 'deal-102', lead_id: 'lead-2', stage: 'proposal', probability: 50, created_at: '2026-03-03T14:00:00Z' },
          ],
        },
        {
          name: 'activities',
          schema: 'public',
          description: 'Appels, rendez-vous et notes de suivi',
          primaryKeys: ['id'],
          rlsEnabled: true,
          rowCount: 92,
          columns: [
            { name: 'id', type: 'uuid', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { name: 'lead_id', type: 'uuid', isPrimary: false, isNullable: false, foreignKey: { targetTable: 'leads', targetColumn: 'id', onDelete: 'CASCADE' } },
            { name: 'activity_type', type: 'text', isPrimary: false, isNullable: false, defaultValue: "'call'" },
            { name: 'notes', type: 'text', isPrimary: false, isNullable: true },
            { name: 'completed', type: 'boolean', isPrimary: false, isNullable: false, defaultValue: 'false' },
            { name: 'created_at', type: 'timestamptz', isPrimary: false, isNullable: false, defaultValue: 'now()' },
          ],
          sampleRows: [
            { id: 'act-1', lead_id: 'lead-1', activity_type: 'call', notes: 'Démo effectuée, client ravi du devis', completed: true, created_at: '2026-03-02T16:00:00Z' },
          ],
        },
      ],
      views: [],
      relationships: [
        { id: 'rel-crm-1', sourceTable: 'deals', sourceColumn: 'lead_id', targetTable: 'leads', targetColumn: 'id', type: 'N:1' },
        { id: 'rel-crm-2', sourceTable: 'activities', sourceColumn: 'lead_id', targetTable: 'leads', targetColumn: 'id', type: 'N:1' },
      ],
      storageBuckets: [
        { id: 'proposals', name: 'proposals', public: false },
      ],
      securityAudit: {
        score: 96,
        rlsDisabledCount: 0,
        missingIndexesCount: 0,
        totalTables: 3,
        issues: [],
      },
    },
  },
  {
    id: 'lovable-booking-service',
    name: 'Lovable Rendez-vous & Réservations',
    description: 'Application Lovable de planning de rendez-vous en ligne, services, créneaux et notifications clients.',
    lovableUrl: 'https://lovable.dev/projects/appointment-booking',
    data: {
      projectInfo: {
        url: 'https://booking-lovable.supabase.co',
        ref: 'booking-lovable-02',
        name: 'Lovable Booking DB',
        region: 'eu-central-1',
        latencyMs: 32,
        checkedAt: new Date().toISOString(),
        connectedVia: 'demo_preset',
      },
      tables: [
        {
          name: 'services',
          schema: 'public',
          description: 'Prestations et forfaits réservables',
          primaryKeys: ['id'],
          rlsEnabled: true,
          rowCount: 12,
          columns: [
            { name: 'id', type: 'uuid', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { name: 'title', type: 'text', isPrimary: false, isNullable: false },
            { name: 'duration_minutes', type: 'integer', isPrimary: false, isNullable: false, defaultValue: '45' },
            { name: 'price_cents', type: 'integer', isPrimary: false, isNullable: false, defaultValue: '6000' },
            { name: 'is_active', type: 'boolean', isPrimary: false, isNullable: false, defaultValue: 'true' },
          ],
          sampleRows: [
            { id: 'srv-1', title: 'Consultation Stratégique', duration_minutes: 60, price_cents: 12000, is_active: true },
            { id: 'srv-2', title: 'Audit Technique Express', duration_minutes: 30, price_cents: 7500, is_active: true },
          ],
        },
        {
          name: 'bookings',
          schema: 'public',
          description: 'Réservations clients validées',
          primaryKeys: ['id'],
          rlsEnabled: true,
          rowCount: 86,
          columns: [
            { name: 'id', type: 'uuid', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { name: 'service_id', type: 'uuid', isPrimary: false, isNullable: false, foreignKey: { targetTable: 'services', targetColumn: 'id' } },
            { name: 'customer_name', type: 'text', isPrimary: false, isNullable: false },
            { name: 'customer_email', type: 'text', isPrimary: false, isNullable: false },
            { name: 'scheduled_at', type: 'timestamptz', isPrimary: false, isNullable: false },
            { name: 'status', type: 'text', isPrimary: false, isNullable: false, defaultValue: "'confirmed'" },
            { name: 'created_at', type: 'timestamptz', isPrimary: false, isNullable: false, defaultValue: 'now()' },
          ],
          sampleRows: [
            { id: 'bkg-1', service_id: 'srv-1', customer_name: 'Camille Leroy', customer_email: 'camille@example.com', scheduled_at: '2026-03-10T14:00:00Z', status: 'confirmed', created_at: '2026-03-01T10:00:00Z' },
          ],
        },
      ],
      views: [],
      relationships: [
        { id: 'rel-bkg-1', sourceTable: 'bookings', sourceColumn: 'service_id', targetTable: 'services', targetColumn: 'id', type: 'N:1' },
      ],
      storageBuckets: [],
      securityAudit: {
        score: 98,
        rlsDisabledCount: 0,
        missingIndexesCount: 0,
        totalTables: 2,
        issues: [],
      },
    },
  },
];
